version: '3.8'

services:


  flask:
    build: ./flask_app
    container_name: flask_app
    ports:
      - "5000:80"
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db

    